name: CI-CD

on:
  push:
    branches:
      - main
env:
      IMAGE_NAME: fastapi
      PROJECT_ID: ${{secrets.GOOGLE_PROJECT}}
      SERVICE_ACCOUNT_KEY: ${{secrets.GOOGLE_APPLICATION_CREDENTIALS}}

jobs:
  CI:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with: 
          python-version: '3.12'

      - name: Install Dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Run static code with flake8
        run: |
          source venv/bin/activate
          flake8 src/main.py
          flake8 src/classes/classes.py
          flake8 src/configurations/config.py
          flake8 src/Input/preprocessors.py

  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: code checkout
        uses: actions/checkout@v2
    
      - name: prueba
        run: |
          echo $PROJECT_ID

